src/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import theme.views
import vuln.urls


urlpatterns = [
    url(r'^$', theme.views.home, name='home'),
    url(r'^vuln/', include(vuln.urls, namespace='vuln')),
    url(r'^admin/', include(admin.site.urls)),
]

src/vuln/urls.py
from django.conf.urls import patterns, url
#from django.contrib import admin

from vuln import views

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^vuln_view/(?P<pk>\d+)$', views.vuln_view, name='vuln_view'),
    url(r'^vuln_new$', views.vuln_create, name='vuln_new'),
    url(r'^vuln_edit/(?P<pk>\d+)$', views.vuln_update, name='vuln_edit'),
    url(r'^vuln_delete/(?P<pk>\d+)$', views.vuln_delete, name='vuln_delete'),
]

src/theme/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/vuln/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Vuln(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    afetado = models.CharField(max_length=50)
    severidade = models.CharField(max_length=10)
    status = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('vuln:vuln_edit', kwargs={'pk': self.pk})

src/theme/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request, template_name='home.html'):
    return render(request, template_name)

src/vuln/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from .models import Vuln

# ========== Forms =========

    # name = models.CharField(max_length=100)
    # desc = models.TextField()
    # afetado = models.CharField(max_length=50)
    # severidade = models.CharField(max_length=10)
    # status 


class VulnForm(ModelForm):
    class Meta:
        model = Vuln
        fields = ['name', 'desc', 'afetado', 'severidade', 'status']


# ========== Home =========

def home(request, template_name='vuln/home.html'):
    vulns = Vuln.objects.all()
    ctx = {}
    ctx['vulns'] = vulns
    return render(request, template_name, ctx)
    

# ========== vuln CRUD =========

def vuln_view(request, pk, template_name='vuln/vuln_view.html'):
    vuln = get_object_or_404(Vuln, pk=pk)
    ctx = {}
    ctx["vuln"] = vuln
    return render(request, template_name, ctx)

def vuln_create(request, template_name='vuln/vuln_form.html'):
    form = VulnForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('vuln:home')
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

def vuln_update(request, pk, template_name='vuln/vuln_form.html'):
    vuln = get_object_or_404(Vuln, pk=pk)
    form = VulnForm(request.POST or None, instance=vuln)
    if form.is_valid():
        form.save()
        return redirect('vuln:home')
    ctx = {}
    ctx["form"] = form
    ctx["vuln"] = vuln
    return render(request, template_name, ctx)

def vuln_delete(request, pk, template_name='vuln/vuln_confirm_delete.html'):
    vuln = get_object_or_404(Vuln, pk=pk)    
    if request.method=='POST':
        vuln.delete()
        return redirect('vuln:home')
    ctx = {}
    ctx["object"] = vuln
    ctx["vuln"] = vuln
    return render(request, template_name, ctx)

src/theme/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Problema2: {% block title %}Olá{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >

    <link rel='stylesheet' href='{% static "css/base.css" %}' />
</head>

<body>

<div id="wrapper">
    <h1><a href="{% url 'home' %}">Início</a></h1>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</div><!-- wrapper -->

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

src/theme/templates/home.html
{% extends "base.html" %}

{% block content %}

<ul>

<p><a href="{% url 'vuln:home' %}">Vulnerabilidades</a></p>

</ul>

{% endblock %}

src/vuln/templates/vuln/home.html
{% extends "base.html" %}

{% block title %}Vulns{% endblock %}

{% block content %}
{% include "vuln/nav.html" %}

<p>Lista de Vulnerabilidades
<a href="{% url 'vuln:vuln_new' %}" class="btn btn-primary" role="button">Novo</a>
</p>
<div class="row">
    <div class="col-md-6">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Desc</th>
                    <th>Ativo afetado</th>
                    <th>Severidade</th>
                    <th>Status</th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                {% for vuln in vulns %}
                    <tr>
                    <td>{{ vuln.name }}</td>
                    <td>{{ vuln.desc|truncatechars_html:40 }}</td>
                    <td>{{ vuln.afetado }}</td>
                    <td>{{ vuln.severidade }}</td>
                    <td>{{ vuln.status }}</td>
                    <td>
                        <a href="{% url 'vuln:vuln_view' vuln.id %}" class="btn btn-xs btn-default" role="button">Detalhes</a>
                        <a href="{% url 'vuln:vuln_edit' vuln.id %}" class="btn btn-xs btn-warning" role="button">Editar</a>
                        <a href="{% url 'vuln:vuln_delete' vuln.id %}" class="btn btn-xs btn-danger" role="button">Deletar</a>
                    </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

src/vuln/templates/vuln/nav.html
<h2>
<a href="{% url 'vuln:home' %}" class="btn btn-lg btn-link" role="button">Vulnerabilidades</a>
{% if vuln %}
&gt; <a href="{% url 'vuln:vuln_view' vuln.id %}">{{ vuln.name }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>

src/vuln/templates/vuln/vuln_confirm_delete.html
{% extends "base.html" %}


{% block content %}
{% include "vuln/nav.html" with vuln=vuln title="Delete" %}
<form method="post">{% csrf_token %}
    Are you sure you want to DELETE "{{ object }}" ?
    <input type="submit" class="btn btn-danger" value="Sim" />
</form>
{% endblock %}

src/vuln/templates/vuln/vuln_form.html
{% extends "base.html" %}


{% block content %}
{% include "vuln/nav.html" with vuln=vuln title="Edit" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="OK" />
</form>
{% endblock %}

src/vuln/templates/vuln/vuln_view.html
{% extends "base.html" %}


{% block content %}
{% include "vuln/nav.html" with vuln=vuln title="Detalhes" %}

<h2>Descrição</h2>
<p>
{{ vuln.desc }}
</p>

{% endblock %}